"""empty message

Revision ID: 9a7d5f7f9e98
Revises: cf908127ddb4
Create Date: 2020-03-23 20:56:16.067053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a7d5f7f9e98'
down_revision = 'cf908127ddb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_roadlu')
    op.drop_table('gps_ic_merge_bas_ic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_ic_merge_bas_ic',
    sa.Column('CARDID', mysql.TEXT(), nullable=True),
    sa.Column('CARDTYPE_NAME', mysql.TEXT(), nullable=True),
    sa.Column('TXNDATE', mysql.DATETIME(), nullable=True),
    sa.Column('TXNAMT', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('BUSID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('bus_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('line_id', mysql.TEXT(), nullable=True),
    sa.Column('seconds', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('second_diff', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('IS_STATION', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('STATION_NAME', mysql.TEXT(), nullable=True),
    sa.Column('banci_csig', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('station_roadlu',
    sa.Column('FID', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('linename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sxxid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stopid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stopname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lng', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FID_', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('RoadName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GHDLDJ', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GH_width', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('XZ_width', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('JDCDS', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Finished', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Shape_Leng', mysql.VARCHAR(length=255), nullable=True),
    mysql_default_charset='gbk',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    # ### end Alembic commands ###
