"""empty message

Revision ID: cf908127ddb4
Revises: 
Create Date: 2020-03-23 18:10:47.895103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf908127ddb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gps_ic_merge_bas_ic')
    op.drop_table('station_roadlu')
    op.drop_table('user_mysql')
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_column('user', 'age')
    op.create_table('user_mysql',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('station_roadlu',
    sa.Column('FID', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('linename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sxxid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stopid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stopname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lng', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FID_', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('RoadName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GHDLDJ', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GH_width', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('XZ_width', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('JDCDS', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Finished', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Shape_Leng', mysql.VARCHAR(length=255), nullable=True),
    mysql_default_charset='gbk',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('gps_ic_merge_bas_ic',
    sa.Column('CARDID', mysql.TEXT(), nullable=True),
    sa.Column('CARDTYPE_NAME', mysql.TEXT(), nullable=True),
    sa.Column('TXNDATE', mysql.DATETIME(), nullable=True),
    sa.Column('TXNAMT', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('BUSID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('bus_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('line_id', mysql.TEXT(), nullable=True),
    sa.Column('seconds', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('second_diff', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('IS_STATION', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('STATION_NAME', mysql.TEXT(), nullable=True),
    sa.Column('banci_csig', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
